version: '3'

services:
  #Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      - redis
      - celery_beat
      - celery_worker

  # PostgreSQL
  pgdb:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./pddata:/var/lib/postgresql/data

  # Redis
  redis:
    image: "redis"
    ports:
      - "6380:6379"

  # Celery beat
  celery_beat:
    build: .
    command: celery -A config beat -l info -S django
    volumes:
      - .:/app

  # Celery worker
  celery_worker:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
