# Generated by Django 4.2.9 on 2024-01-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.TextField(verbose_name='Поощрение')),
            ],
            options={
                'verbose_name': 'Поощрение',
                'verbose_name_plural': 'Поощрения',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200, verbose_name='Место выполнения привычки')),
                ('execution_time', models.DateTimeField(verbose_name='Время и дата выполнения привычки')),
                ('action', models.TextField(verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(default=1, verbose_name='Периодичность в днях')),
                ('time_to_complete', models.PositiveIntegerField(verbose_name='Время на выполнение (сек.)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.award', verbose_name='Вознаграждение')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
